
name: build-node-ci

on:

  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x]
        
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install

      - name: Build Project
        run: npm run build
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.run_id }}
          path: dist/
          retention-days: 14
          
  deploy:
    name: Dummy Deploy
    needs: build
    runs-on: ${{ vars.VM_IMAGEN }}
    environment:
      name: node-backend-dev
      url: https://www.google.com

    steps:
      - name: Descarga artefacto
        uses: actions/download-artifact@v4
        with:
          name:  ${{ github.run_id }}

      - name: Imprimir variables de entorno
        run: |
          echo "Secret VAR: ${{ secrets.SECRET_DEV }}"
          cho "Environment VAR: ${{ vars.PATH_URL }}"
