name: Usar un Template

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Usar template o action reutilizable
        uses: paupaipai/loteria-back-node/.github/actions/helpers/hello-word@main
          
